#!/usr/bin/env bun
//
// bny lock-tests — lock adversarial tests as immutable artifacts
//
// copies test files generated by gemini to tests/adversarial/<feature>/
// and registers the path in guardrails as protected.
//
// these tests are a one-way ratchet: once locked, they define the floor
// of correctness. implementation must rise to meet them.
//
// usage:
//   bny lock-tests                     # lock tests for current feature
//   bny lock-tests 001-auth            # explicit feature
//

import { existsSync, mkdirSync, cpSync, readFileSync, writeFileSync, readdirSync } from "node:fs"
import { resolve, relative } from "node:path"
import { find_root, current_feature } from "./lib/feature.ts"
import { detect_project_type } from "./lib/project.ts"

export async function main(argv: string[]): Promise<number> {
  let target: string | null = null

  for (const arg of argv) {
    if (arg === "--help" || arg === "-h") {
      process.stdout.write("usage: bny lock-tests [feature-name]\n")
      process.stdout.write("\nlock adversarial tests — copies to tests/adversarial/<feature>/\n")
      return 0
    } else if (!arg.startsWith("-")) {
      target = arg
    }
  }

  const root = find_root()
  const name = target || current_feature()

  if (!name) {
    process.stderr.write("error: no feature specified and not on a feature branch\n")
    return 1
  }

  // -- find test files --

  const project = detect_project_type(root)
  const test_dir = resolve(root, project.test_dir)

  if (!existsSync(test_dir)) {
    process.stderr.write(`error: test directory ${project.test_dir} does not exist\n`)
    return 1
  }

  // -- copy to adversarial/ --

  const adversarial_dir = resolve(root, "tests", "adversarial", name)
  mkdirSync(adversarial_dir, { recursive: true })

  let locked = 0
  function walk(dir: string) {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.name === "adversarial" || entry.name === "node_modules" || entry.name === "fixtures") continue
      const abs = resolve(dir, entry.name)
      if (entry.isDirectory()) {
        walk(abs)
      } else if (/\.(test|spec)\.(ts|js|tsx|jsx)$/.test(entry.name)) {
        const rel = relative(test_dir, abs)
        const dest = resolve(adversarial_dir, rel)
        mkdirSync(resolve(dest, ".."), { recursive: true })
        cpSync(abs, dest, { force: true })
        locked++
      }
    }
  }
  walk(test_dir)

  if (locked === 0) {
    process.stderr.write(`warning: no test files found to lock\n`)
    return 0
  }

  // -- register in guardrails --

  const guardrails_path = resolve(root, "bny", "guardrails.json")
  if (existsSync(guardrails_path)) {
    try {
      const guardrails = JSON.parse(readFileSync(guardrails_path, "utf-8"))

      // add protected pattern for this feature's adversarial tests
      if (!guardrails.protected_patterns) guardrails.protected_patterns = []
      const pattern = `tests/adversarial/${name}/**`
      if (!guardrails.protected_patterns.includes(pattern)) {
        guardrails.protected_patterns.push(pattern)
        writeFileSync(guardrails_path, JSON.stringify(guardrails, null, 2) + "\n")
        process.stderr.write(`[lock-tests] added ${pattern} to guardrails.json\n`)
      }
    } catch {
      process.stderr.write(`warning: could not update guardrails.json\n`)
    }
  }

  process.stderr.write(`[lock-tests] locked ${locked} test file(s) to tests/adversarial/${name}/\n`)
  return 0
}

if (import.meta.main) process.exit(await main(process.argv.slice(2)))
